function http_request_struct = http_createRequestStruct(url,method,body,headers)
%http_createRequestStruct 
%
%   http_request_struct = http_createRequestStruct(url,method,body,headers)

http_request_struct = struct(...
    'url',      url, ...
    'method',   method, ...
    'body',     body, ...
    'headers',  headers);        