function book_struct = mendeleyl_conv_ToBook(entry)

%ALL FIELDS
%========================
%     'authors'
%     'cast'
%     'city'
%     'dateAccessed'
%     'discipline'
%     'doi'
%     'editors'
%     'files'
%     'id'
%     'identifiers'
%     'isbn'
%     'issn'
%     'issue'
%     'keywords'
%     'mendeley_url'
%     'month'
%     'pages'
%     'producers'
%     'publication_outlet'
%     'published_in'
%     'publisher'
%     'source_type'
%     'subdiscipline'
%     'tags'
%     'title'
%     'translators'
%     'type'
%     'url'
%     'volume'
%     'year'

